servesAll(american, salad, steak, sandwiches, burgers,  fried_chicken)
servesAll(burger_place, burgers, fries, onion_rings)
servesAll(chinese, eggrolls, rice, shrimp, soup, noodles)
serves(Kind, Dish)
servesAll(Kind, Dishes)
member(Dish, Dishes)
